name: Run Jest Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21' # Updated to Node.js 18 for compatibility

      - name: Create directories
        run: mkdir -p src/environments

      - name: Create config.ts
        run: |
          echo "export const config = {" > src/environments/config.ts
          echo "  client_id: 'your_client_id'," >> src/environments/config.ts
          echo "  redirect_url: 'your_redirect_url'," >> src/environments/config.ts
          echo "  api_url: 'your_api_url'," >> src/environments/config.ts
          echo "  discord_url: 'your_discord_url'" >> src/environments/config.ts
          echo "};" >> src/environments/config.ts

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
